---
title: "Visit Scotland Tourism Analysis"
author: "Barry O Dea"
date: "13/09/2021"
output: html_document
---


# Read in the data and explore
```{r}
library(tidyverse)
library(janitor)
library(here)
```

```{r}
regional_domestic_tourism <- read_csv(here("raw_data/regional_domestic_tourism.csv")) %>% 
  clean_names()
accomm_occupancy <- read_csv(here("raw_data/scottish_accomodation_occupancy.csv")) %>% 
  clean_names()
day_visit_activities <- read_csv(here("raw_data/tourism_day_visits_activities.csv")) %>% 
  clean_names()
day_visit_demographics <- read_csv(here("raw_data/tourism_day_visits_demographics.csv")) %>% 
  clean_names()
day_visit_location <- read_csv(here("raw_data/tourism_day_visits_location.csv")) %>% 
  clean_names()
day_visit_tramsport <- read_csv(here("raw_data/tourism_day_visits_transport.csv")) %>% 
  clean_names()
location_data <- read_csv(here("raw_data/Datazone2011lookup.csv")) %>% 
  clean_names()

```

# Look at the data for the first question on activities creating the most income
```{r}
glimpse(day_visit_activities)

unique(day_visit_activities$breakdown_of_domestic_tourism)
```

```{r}
day_visit_activities_clean <-  day_visit_activities %>% 
  rename(year = date_code) %>% 
  filter(breakdown_of_domestic_tourism == "Expenditure") %>% 
  group_by(tourism_activity, year) %>% 
  mutate(expenditure_in_millions = sum(value)) 
```


 ## write clean file to new folder
 
```{r}
write_csv(day_visit_activities_clean, here("clean_data/day_visit_activities_clean.csv"))
```


# Look at the data for the first question on activities creating the most income
```{r}
day_visit_activities_visits_clean <-  day_visit_activities %>% 
  rename(year = date_code) %>% 
  filter(breakdown_of_domestic_tourism == "Visits") %>% 
  group_by(tourism_activity, year) %>% 
  mutate(expenditure_in_millions = sum(value)) 
```


```{r}
demographics_long <- day_visit_demographics %>% 
  pivot_longer(cols = c(age:social_grade), names_to = "category", values_to = "status") %>% 
  filter(status != "All") %>% 
  arrange(date_code, breakdown_of_domestic_tourism, category)

demographics_long 
```

```{r}
demographics_long %>% 
  group_by(date_code, breakdown_of_domestic_tourism) %>% 
  summarise(sum = sum(value))

demographics_long %>% 
  distinct(status)
```


```{r}
library(modelr)

# visualisation packages
library(GGally)
```

```{r}
demographics_long %>% 
  select(-c("date_code", "feature_code", "measurement", "status")) %>% 
  filter(breakdown_of_domestic_tourism == "Visits") %>% 
  ggpairs()
```
```{r}
glimpse(demographics_visist)
```


```{r}
demographics_visist <- demographics_long %>% 
  select(-c("date_code", "feature_code", "measurement")) %>% 
  mutate(units = as.factor(units),
         breakdown_of_domestic_tourism = as.factor(breakdown_of_domestic_tourism),
         category = as.factor(category),
         status = as.factor(category)) %>% 
  filter(breakdown_of_domestic_tourism == "Visits")
```

```{r}
library(leaps)

regsubsets_forward <- regsubsets(value ~ ., data = demographics_visist, method = "forward")
```

```{r}
demographics_visist %>% 
  ggpairs()
```

```{r}
mod1a <- lm(value ~ category, data = demographics_visist)
mod1a
```

```{r}
summary(mod1a)
```

```{r}
day_visit_demographics %>% 
  glimpse()

visits_demographics <- day_visit_demographics %>% 
   select(-c("date_code", "feature_code", "measurement")) %>% 
  mutate(units = as.factor(units),
         breakdown_of_domestic_tourism = as.factor(breakdown_of_domestic_tourism),
         age = as.factor(age),
         marital_status = as.factor(marital_status),
         gender = as.factor(gender),
         employment_status = as.factor(employment_status),
         children = as.factor(children),
         access_to_car = as.factor(access_to_car),
         social_grade = as.factor(social_grade)) %>% 
  filter(breakdown_of_domestic_tourism == "Visits")
```

```{r}
visits_demographics %>% 
  ggpairs()
```



```{r}
mod1a <- lm(value ~ age + access_to_car + children, data = visits_demographics)
summary(mod1a)
```

```{r}
exp_demographics <- day_visit_demographics %>% 
   select(-c("date_code", "feature_code", "measurement")) %>% 
  mutate(units = as.factor(units),
         breakdown_of_domestic_tourism = as.factor(breakdown_of_domestic_tourism),
         age = as.factor(age),
         marital_status = as.factor(marital_status),
         gender = as.factor(gender),
         employment_status = as.factor(employment_status),
         children = as.factor(children),
         access_to_car = as.factor(access_to_car),
         social_grade = as.factor(social_grade)) %>% 
  filter(breakdown_of_domestic_tourism == "Expenditure",
         age != "All")
```

```{r}
regsubsets_forward1 <- regsubsets(value ~ age + gender + access_to_car, data = exp_demographics, nvmax = 20, method = "forward")
regsubsets_forward1 
```

```{r}
sum_regsubsets_forward1 <- summary(regsubsets_forward1)
sum_regsubsets_forward1
```



```{r}
mod1a <- lm(value ~ age, data = exp_demographics)
summary(mod1a)
```

```{r}
exp_demographics %>% 
  filter(age != "All") %>% 
  ggpairs()
```
```{r}
activites_trim <- day_visit_activities_clean %>% 
     select(-c("year", "feature_code", "measurement", "units")) %>% 
  mutate(tourism_activity = as.factor(tourism_activity),
         breakdown_of_domestic_tourism = as.factor(breakdown_of_domestic_tourism)) %>% 
  filter(breakdown_of_domestic_tourism == "Expenditure") %>% 
  clean_names()
  
```

```{r}
library(fastDummies)

activites_trim <- activites_trim %>%  dummy_cols(select_columns = "tourism_activity", remove_first_dummy = TRUE, remove_selected_columns = TRUE)

activities_trim <- activites_trim %>% 
  clean_names() %>% 
  mutate_if(is.integer,as.factor) %>% 
  select(-c(year, expenditure_in_millions, breakdown_of_domestic_tourism))
```

```{r}
alias(lm(value ~ ., data = activities_trim))
```



```{r}
mod2a <- lm(value ~ tourism_activity,  data = activites_trim)
summary(mod2a)
```

```{r}
regsubsets_forward <- regsubsets(value ~ tourism_activity, data = activites_trim, nvmax = 20, method = "forward")
regsubsets_forward 
```


```{r}
sum_regsubsets_forward <- summary(regsubsets_forward)
sum_regsubsets_forward
plot(sum_regsubsets_forward$rsq, type = "b")
```



```{r}
activites_trim %>% 
  summarise_all(funs(sum(is.na(.))))
```

```{r}
age_total <- day_visit_demographics %>% 
  select(-c(marital_status:social_grade, measurement, breakdown_of_domestic_tourism, feature_code)) %>% 
  group_by(date_code, age) %>% 
  summarise(percent= value/sum(value)) 

 
```

```{r}
day_visit_demographics %>% 
  filter(date_code == 2013,
         )
```

