---
title: "Data analysis and visualisations"
author: "Barry O Dea"
date: "13/09/2021"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
day_visit_activities_clean <- read.csv(here("clean_data/day_visit_activities_clean.csv"))

day_visit_activities_clean %>% 
  distinct(units)
```
```{r}
top_expenditure <- day_visit_activities %>% 
  rename(year = date_code) %>% 
  filter(breakdown_of_domestic_tourism == "Expenditure",
         tourism_activity != "All") %>% 
  group_by(tourism_activity, year) %>% 
  summarise(expenditure_in_millions = sum(value))

top_expenditure %>% 
  group_by(tourism_activity) %>% 
  summarise(expenditure_in_millions = sum(expenditure_in_millions)) %>% 
  arrange(desc(expenditure_in_millions))

```



```{r}
day_visit_activities_clean %>% 
  filter(breakdown_of_domestic_tourism == "Expenditure",
         tourism_activity != "All",
         tourism_activity %in% c("Went out for a meal", "Shopping for items that you do not regularly buy", "Visited friends or family for leisure", "Night out to a bar, pub and/or club", "Night out to a bar, pub and/or club", "Outdoor leisure activities e.g. walking, golf"), 
         year %in% c("2017", "2018", "2019")) %>% 
  mutate(tourism_activity = fct_reorder(tourism_activity, desc(expenditure_in_millions))) %>% 
  ggplot() +
  geom_col(aes(x= year, y = expenditure_in_millions, fill = factor(tourism_activity)), position = "dodge", colour = "white") +
  theme(axis.text.x = element_text(face = "bold", angle = 25, hjust = 1, vjust = 1))
```

```{r}
top_expenditure %>% 
  group_by(tourism_activity) %>% 
  summarise(expenditure_in_millions = sum(expenditure_in_millions)) %>% 
  mutate(tourism_activity = fct_reorder(tourism_activity, desc(expenditure_in_millions))) %>% 
  ggplot() + 
  geom_col(aes(x = tourism_activity, y = expenditure_in_millions)) +
  theme(axis.text.x = element_text(size = 7, face = "bold", angle = 45, hjust = 1, vjust = 1))
```

